server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}

  jpa:
    hibernate:
      ddl-auto: none


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method  # 메서드 기준 정렬
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs

