name: Build and Push Backend to GHCR

on:
  push:
    branches:
      - main  # main 브랜치에 push되면 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # 백엔드 코드 가져오기

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Backend JAR
        run: ./gradlew clean build -x test  # 테스트 생략

      - name: Build Docker Image
        run: docker build -t ghcr.io/docker-seo/backend-repo:latest .

      - name: Push Docker Image to GHCR
        run: docker push ghcr.io/docker-seo/backend-repo:latest
